version: '3.7'

services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    env_file: .env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQL_DATABASE
      - MYSQL_USER=$MYSQL_USER
      - MYSQL_PASSWORD=$MYSQL_PASSWORD
    ports:
      - $MYSQL_PORT:$MYSQL_PORT
    volumes:
      - db:/var/lib/touch-events
  adminer:
    image: adminer
    depends_on:
      - mysqldb
    env_file: .env
    restart: always
    ports:
      - $MYSQL_ADMINER_PORT:$MYSQL_ADMINER_PORT

volumes:
  db:
